// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhllxNXJz6dp4KAe6PDWgOjb9cmPQyI8k',
    appId: '1:387202563418:web:b3158c0875cf08fded8763',
    messagingSenderId: '387202563418',
    projectId: 'gesbuk-58f74',
    authDomain: 'gesbuk-58f74.firebaseapp.com',
    storageBucket: 'gesbuk-58f74.appspot.com',
    measurementId: 'G-GTK06SZCZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6boW3_p-wkrjUvCOFuk5W47_MastSPqE',
    appId: '1:387202563418:android:0c4d5d132a9d6e40ed8763',
    messagingSenderId: '387202563418',
    projectId: 'gesbuk-58f74',
    storageBucket: 'gesbuk-58f74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4UaRrePlWB1VIqH5GqsqUSome4NVMJWk',
    appId: '1:387202563418:ios:51eca7d4dd44745aed8763',
    messagingSenderId: '387202563418',
    projectId: 'gesbuk-58f74',
    storageBucket: 'gesbuk-58f74.appspot.com',
    iosClientId: '387202563418-uc05c8qs1tfm5fba1lumb0deuab855uh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGesbukUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4UaRrePlWB1VIqH5GqsqUSome4NVMJWk',
    appId: '1:387202563418:ios:51eca7d4dd44745aed8763',
    messagingSenderId: '387202563418',
    projectId: 'gesbuk-58f74',
    storageBucket: 'gesbuk-58f74.appspot.com',
    iosClientId: '387202563418-uc05c8qs1tfm5fba1lumb0deuab855uh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGesbukUser',
  );
}
